language: node_js
node_js:
- '4'
env:
  matrix:
  - CXX=g++-4.8
  global:
    - GH_REF: github.com/xively/concaria.git
    - secure: tK6LGqITDl160Q8WFV2CpzsNPSygaUElJQNnNN2rNW/umjbhRELBI0VZQI//3SJIMqYLhrOoCNGpJi272Bs6eyfBmBJi2VzvAWVGo685tCJGSKwDGWsPEOoOa3KyA+/aVGAZmkb7jzU5na5DYzKdrklz66yLtaTTLxcOFn5ElAu+pd2zjVk5CsijmRHuB/A1fB/L3Ml5lC8ykPMosqYJv3kL1SZNtTmTa6zwPkaPeIlEiwVXyUyCQqRoDpk0R3Oe8iHAdExZQmypC23uBwhrAXQ7nnTsvsfpWXqlKyX+UBTeMuthHhflXPjsNhCOydwvdyGzVtxRxmyEq7N8uLjCuQCdBAE15H13m7VLW9P5vplp39g6FOXJ4rezw2cZR4OMpvUKM32IhZRGSjjsR4j7XGhftRVz4/ZHDsdIlnWn2JqdDWifZHrntFrGbXjBL5CeVqbq1CR74XtMtIl3O3bRvcWXdX9iPcwjSwdv8U9Ta1v+dyrkUbiVEY8SpDLAqcHYsgvKCf3dRHO4J2zDzhKoaR8mTRtspf+gl6qtfaolw3pSwt1rarf1/nuBop5m/OE8Rd1d2hY+1kQF1YEpoGbPoYKIp1J4msbvL2ORkfylVPSIJRqyaSgbDbkpOKE0hZq7icuamSLv/xS06iF07LOLVw+6q51hgWqsrYQN6L2X1tg=
addons:
  postgresql: '9.4'
services:
- postgresql
before_script:
- psql -d postgres -c 'CREATE DATABASE concaria;'
- npm run syncdb
after_success:
- if [[ $TRAVIS_BRANCH != *"-build"* ]]; then bash ./scripts/push-build.sh; fi
