language: node_js
node_js:
  - "4"
  - "stable"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -d postgres -c 'CREATE DATABASE concaria;'
  - npm run syncdb
